# Generated by Django 5.2.7 on 2025-11-01 00:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('clicked', models.BooleanField(default=False)),
                ('time_to_click', models.FloatField(blank=True, help_text='Seconds from page load to click', null=True)),
            ],
            options={
                'ordering': ['-loaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ButtonClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_elapsed', models.FloatField(help_text='Seconds from page load to click')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='button.pagesession')),
            ],
            options={
                'ordering': ['-clicked_at'],
            },
        ),
    ]
