# Generated by Django 5.2.7 on 2025-11-01 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('button', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesession',
            name='country_code',
            field=models.CharField(blank=True, help_text='ISO 3166-1 alpha-2 country code', max_length=2),
        ),
        migrations.AddField(
            model_name='pagesession',
            name='country_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
