# Generated by Django 5.2.7 on 2025-11-01 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('button', '0002_pagesession_country_code_pagesession_country_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesession',
            name='reclick_attempts',
            field=models.IntegerField(default=0, help_text='Number of times user tried to click after already clicking'),
        ),
        migrations.AddField(
            model_name='pagesession',
            name='referrer',
            field=models.TextField(blank=True, help_text='HTTP Referer header - where visitor came from'),
        ),
    ]
