# Generated by Django 5.2.7 on 2025-11-01 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('button', '0003_pagesession_reclick_attempts_pagesession_referrer'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesession',
            name='browser_name',
            field=models.CharField(blank=True, help_text='Browser name (Chrome, Firefox, Safari, etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='pagesession',
            name='browser_version',
            field=models.CharField(blank=True, help_text='Browser version', max_length=50),
        ),
    ]
